<?php
$data = array (
  0 => 
  array (
    'cat_id' => '22',
    'cat_name' => '品酒师推荐促销',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '品酒师推荐促销',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  1 => 
  array (
    'cat_id' => '28',
    'cat_name' => '网站新闻',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '3',
    'aricle_num' => '0',
  ),
  2 => 
  array (
    'cat_id' => '31',
    'cat_name' => '大课堂',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  3 => 
  array (
    'cat_id' => '1',
    'cat_name' => '系统分类',
    'cat_type' => '2',
    'keywords' => '',
    'cat_desc' => '系统保留分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  4 => 
  array (
    'cat_id' => '32',
    'cat_name' => '美妆教室',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '12',
  ),
  5 => 
  array (
    'cat_id' => '33',
    'cat_name' => '保健常识',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  6 => 
  array (
    'cat_id' => '34',
    'cat_name' => '导师推荐',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  7 => 
  array (
    'cat_id' => '23',
    'cat_name' => '秀当公益',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '51',
    'show_in_nav' => '1',
    'parent_id' => '0',
    'has_children' => '4',
    'aricle_num' => '0',
  ),
  8 => 
  array (
    'cat_id' => '2',
    'cat_name' => '网店信息',
    'cat_type' => '3',
    'keywords' => '',
    'cat_desc' => '网店信息分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  9 => 
  array (
    'cat_id' => '3',
    'cat_name' => '常见问题分类',
    'cat_type' => '4',
    'keywords' => '',
    'cat_desc' => '常见问题分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '8',
    'aricle_num' => '0',
  ),
  10 => 
  array (
    'cat_id' => '13',
    'cat_name' => '关于秀当',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '关于秀当',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '4',
  ),
  11 => 
  array (
    'cat_id' => '29',
    'cat_name' => '红酒文化',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '4',
  ),
  12 => 
  array (
    'cat_id' => '14',
    'cat_name' => '新手课堂',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '新手课堂',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  13 => 
  array (
    'cat_id' => '30',
    'cat_name' => '加盟我们',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  14 => 
  array (
    'cat_id' => '15',
    'cat_name' => '支付方式',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  15 => 
  array (
    'cat_id' => '16',
    'cat_name' => '配送方式',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  16 => 
  array (
    'cat_id' => '17',
    'cat_name' => '售后服务',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  17 => 
  array (
    'cat_id' => '18',
    'cat_name' => '帮助中心',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  18 => 
  array (
    'cat_id' => '26',
    'cat_name' => '学校征集',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '23',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  19 => 
  array (
    'cat_id' => '27',
    'cat_name' => '我们的行动',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '23',
    'has_children' => '0',
    'aricle_num' => '4',
  ),
  20 => 
  array (
    'cat_id' => '24',
    'cat_name' => '关于我们',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '23',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  21 => 
  array (
    'cat_id' => '25',
    'cat_name' => '最新资讯',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '23',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  22 => 
  array (
    'cat_id' => '21',
    'cat_name' => '媒体报道2',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '媒体报道',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '28',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  23 => 
  array (
    'cat_id' => '19',
    'cat_name' => '最新公告',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '最新公告',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '28',
    'has_children' => '0',
    'aricle_num' => '4',
  ),
  24 => 
  array (
    'cat_id' => '20',
    'cat_name' => '促销活动',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '促销活动',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '28',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
);
?>